"""Initial migration

Revision ID: 26971d5ada94
Revises: 
Create Date: 2025-12-09 11:50:05.092983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '26971d5ada94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_catalog',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('icono_primeng', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regions_geometry', 'regions', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('report_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('periodos', sa.JSON(), nullable=False),
    sa.Column('class_filters', sa.JSON(), nullable=True),
    sa.Column('segment_ids', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregation_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('total_area_m2', sa.Float(), nullable=False),
    sa.Column('green_coverage', sa.Float(), nullable=False),
    sa.Column('distribution_json', sa.JSON(), nullable=False),
    sa.Column('trend_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'periodo', name='uq_region_periodo')
    )
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=False),
    sa.Column('epsg', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=128), nullable=False),
    sa.Column('raster_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subregions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subregions_geometry', 'subregions', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('is_manual_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segments_geometry', 'segments', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_segments_region_period_class', 'segments', ['region_id', 'periodo', 'class_id'], unique=False)
    op.create_index(op.f('ix_segments_periodo'), 'segments', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_periodo'), table_name='segments')
    op.drop_index('idx_segments_region_period_class', table_name='segments')
    op.drop_index('idx_segments_geometry', table_name='segments', postgresql_using='gist')
    op.drop_table('segments')
    op.drop_index('idx_subregions_geometry', table_name='subregions', postgresql_using='gist')
    op.drop_table('subregions')
    op.drop_table('scenes')
    op.drop_table('aggregation_summary')
    op.drop_table('report_requests')
    op.drop_index('idx_regions_geometry', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    op.drop_table('class_catalog')
    # ### end Alembic commands ###
