"""Add pixel coverage analysis tables

Revision ID: fbe3768827e8
Revises: 26971d5ada94
Create Date: 2025-12-11 21:32:43.701983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbe3768827e8'
down_revision: Union[str, Sequence[str], None] = '26971d5ada94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('total_pixels', sa.Integer(), nullable=False),
    sa.Column('image_resolution', sa.String(length=50), nullable=False),
    sa.Column('coverage_by_class', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segmentation_created_at', 'segmentation_results', ['created_at'], unique=False)
    op.create_index('idx_segmentation_scene_id', 'segmentation_results', ['scene_id'], unique=False)
    op.create_table('segmentation_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segmentation_result_id', sa.UUID(), nullable=False),
    sa.Column('dominant_class_name', sa.String(length=255), nullable=True),
    sa.Column('dominant_class_percentage', sa.Float(), nullable=True),
    sa.Column('second_class_name', sa.String(length=255), nullable=True),
    sa.Column('second_class_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segmentation_result_id'], ['segmentation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segmentation_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segmentation_summaries')
    op.drop_index('idx_segmentation_scene_id', table_name='segmentation_results')
    op.drop_index('idx_segmentation_created_at', table_name='segmentation_results')
    op.drop_table('segmentation_results')
    # ### end Alembic commands ###
